CREATE TABLE [dbo].[Person](
  [Id] UNIQUEIDENTIFIER NOT NULL 
      CONSTRAINT [DF_Person_Id] DEFAULT NEWSEQUENTIALID(),
  [Firstname] NVARCHAR(100) NOT NULL,
  [Lastname]  NVARCHAR(100) NOT NULL,
  [Email] NVARCHAR(100) NOT NULL,
  CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED ([Id] ASC)
);
